// Package formats implements the CLI's format-module tooling: resolving
// format names to Go packages, generating the tool-owned formats.go a
// scaffolded project registers its parsers in, and materializing each
// format's contract docs (schema.md + golden fixtures) into the project's
// docs area so a coding agent finds them locally.
//
// A "format" is a Go package exposing the fuego-formats convention —
// Parser(opts ...Option) core.Parser — one package per format. Short names
// resolve by convention to github.com/gofuego/fuego-formats/<name>;
// "markdown" is the single alias, resolving to the engine's first-party
// parser package; any full package path is accepted (third-party formats),
// so the resolver has no hardcoded module list beyond the alias.
package formats

import (
	"bytes"
	"fmt"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// Format is one resolved format module: the package to import, the
// identifier its Parser() is called through, and the short name its docs
// live under (docs/formats/<Name>/).
type Format struct {
	Name       string
	ImportPath string
	Symbol     string
}

// engineImport is the one import formats.go always carries besides the
// format packages.
const engineImport = "github.com/gofuego/fuego/engine"

// markdownImport is the engine's first-party markdown parser package — the
// resolver's single alias.
const markdownImport = "github.com/gofuego/fuego/parsers/markdown"

// Resolve maps a format name to its package. Short names resolve by
// convention; "markdown" is the alias for the engine's first-party parser;
// a name containing '/' is taken as a full package path (the parser package
// itself, which by the fuego-formats convention is the module root).
func Resolve(name string) (Format, error) {
	return ResolveWithSymbol(name, "")
}

// ResolveWithSymbol is Resolve with an explicit package identifier for
// third-party paths whose last element is not a valid Go identifier
// (e.g. github.com/acme/fuego-terraform → --symbol terraform).
func ResolveWithSymbol(name, symbol string) (Format, error) {
	name = strings.TrimSpace(name)
	if name == "" {
		return Format{}, fmt.Errorf("empty format name")
	}

	if name == "markdown" {
		return withSymbol(Format{Name: "markdown", ImportPath: markdownImport, Symbol: "markdown"}, symbol)
	}

	if !strings.Contains(name, "/") {
		if !isGoIdentifier(name) {
			return Format{}, fmt.Errorf("format name %q is not a valid Go identifier", name)
		}
		return withSymbol(Format{
			Name:       name,
			ImportPath: "github.com/gofuego/fuego-formats/" + name,
			Symbol:     name,
		}, symbol)
	}

	base := path.Base(name)
	f := Format{Name: base, ImportPath: name, Symbol: base}
	if symbol == "" && !isGoIdentifier(base) {
		return Format{}, fmt.Errorf(
			"cannot derive a package identifier from %q (got %q); pass --symbol with the package's name", name, base)
	}
	return withSymbol(f, symbol)
}

func withSymbol(f Format, symbol string) (Format, error) {
	if symbol == "" {
		return f, nil
	}
	if !isGoIdentifier(symbol) {
		return Format{}, fmt.Errorf("symbol %q is not a valid Go identifier", symbol)
	}
	f.Symbol = symbol
	return f, nil
}

func isGoIdentifier(s string) bool {
	if s == "" {
		return false
	}
	for i, r := range s {
		switch {
		case r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r == '_':
		case r >= '0' && r <= '9':
			if i == 0 {
				return false
			}
		default:
			return false
		}
	}
	return true
}

// FileName is the tool-owned registration file in a project root.
const FileName = "formats.go"

// RenderFile renders the tool-owned formats.go for the given format set, in
// order. A named import is emitted only when the symbol differs from the
// import path's base element.
func RenderFile(fmts []Format) []byte {
	var b bytes.Buffer
	b.WriteString("// Code generated by fuego; DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// This file is owned by the fuego CLI: `fuego formats add <name>` regenerates\n")
	b.WriteString("// it, and `fuego formats sync` refreshes docs/formats/ from the pinned module\n")
	b.WriteString("// versions. Hand edits will be overwritten.\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n")
	fmt.Fprintf(&b, "\t%q\n", engineImport)
	if len(fmts) > 0 {
		b.WriteString("\n")
	}
	for _, f := range fmts {
		if f.Symbol != path.Base(f.ImportPath) {
			fmt.Fprintf(&b, "\t%s %q\n", f.Symbol, f.ImportPath)
		} else {
			fmt.Fprintf(&b, "\t%q\n", f.ImportPath)
		}
	}
	b.WriteString(")\n\n")
	b.WriteString("// registerFormats registers the project's format parsers, one per installed\n")
	b.WriteString("// format module. main.go calls it once before eng.Run.\n")
	b.WriteString("func registerFormats(eng *engine.Engine) {\n")
	for _, f := range fmts {
		fmt.Fprintf(&b, "\teng.Register(%s.Parser())\n", f.Symbol)
	}
	b.WriteString("}\n")
	return b.Bytes()
}

// WriteFile renders and writes formats.go into dir.
func WriteFile(dir string, fmts []Format) error {
	return os.WriteFile(filepath.Join(dir, FileName), RenderFile(fmts), 0644)
}

// ParseFile reads a project's formats.go back into the format set, mapping
// each import through the resolver's conventions (the file is tool-owned, so
// its shape is known). Returns os.ErrNotExist if the file is absent — the
// project predates the convention.
func ParseFile(dir string) ([]Format, error) {
	p := filepath.Join(dir, FileName)
	if _, err := os.Stat(p); err != nil {
		return nil, err
	}
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, p, nil, parser.ImportsOnly)
	if err != nil {
		return nil, fmt.Errorf("parsing %s: %w", FileName, err)
	}

	var fmts []Format
	for _, imp := range file.Imports {
		importPath, err := strconv.Unquote(imp.Path.Value)
		if err != nil || importPath == engineImport {
			continue
		}
		f := Format{ImportPath: importPath, Symbol: path.Base(importPath)}
		if imp.Name != nil {
			f.Symbol = imp.Name.Name
		}
		switch {
		case importPath == markdownImport:
			f.Name = "markdown"
		default:
			f.Name = path.Base(importPath)
		}
		fmts = append(fmts, f)
	}
	return fmts, nil
}

// DocsDir is the project docs area format contracts materialize into.
const DocsDir = "docs/formats"

// MaterializeDocs copies a format's contract docs — schema.md,
// DEPENDENCIES.md when present, and the testdata/ golden fixtures — from the
// resolved package source (the module cache, at whatever version the
// project's go.mod pins) into docs/formats/<name>/. The package must be
// resolvable in the project (fetched by `go get`), so callers run it after
// dependency resolution.
func MaterializeDocs(projectDir string, f Format) error {
	pkgDir, err := goPackageDir(projectDir, f.ImportPath)
	if err != nil {
		return fmt.Errorf("locating %s source: %w", f.ImportPath, err)
	}
	return materializeFromDir(pkgDir, projectDir, f)
}

// materializeFromDir is MaterializeDocs with the package source directory
// already resolved (the seam unit tests use).
func materializeFromDir(pkgDir, projectDir string, f Format) error {
	dst := filepath.Join(projectDir, filepath.FromSlash(DocsDir), f.Name)
	if err := os.MkdirAll(dst, 0755); err != nil {
		return err
	}

	if err := copyFile(filepath.Join(pkgDir, "schema.md"), filepath.Join(dst, "schema.md")); err != nil {
		return fmt.Errorf("format %s ships no schema.md contract: %w", f.Name, err)
	}
	// Optional extras.
	copyFile(filepath.Join(pkgDir, "DEPENDENCIES.md"), filepath.Join(dst, "DEPENDENCIES.md"))
	if err := copyDir(filepath.Join(pkgDir, "testdata"), filepath.Join(dst, "testdata")); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("copying %s fixtures: %w", f.Name, err)
	}
	return nil
}

// WriteIndex regenerates the tool-owned docs/formats/README.md index the
// scaffolded CLAUDE.md points at.
func WriteIndex(projectDir string, fmts []Format) error {
	dir := filepath.Join(projectDir, filepath.FromSlash(DocsDir))
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	sorted := append([]Format(nil), fmts...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var b bytes.Buffer
	b.WriteString("# Installed format contracts\n\n")
	b.WriteString("Generated by fuego; do not edit. Each installed format module's contract —\n")
	b.WriteString("its `schema.md` (claims, envelope keys, node types, tree shape, slug rules,\n")
	b.WriteString("stability) and golden fixtures — is materialized here at the version pinned\n")
	b.WriteString("in go.mod. Regenerate with `fuego formats sync`; install more with\n")
	b.WriteString("`fuego formats add <name>`.\n\n")
	b.WriteString("| Format | Package | Contract | Fixtures |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, f := range sorted {
		fixtures := "—"
		if _, err := os.Stat(filepath.Join(dir, f.Name, "testdata")); err == nil {
			fixtures = fmt.Sprintf("[testdata/](%s/testdata)", f.Name)
		}
		fmt.Fprintf(&b, "| %s | `%s` | [schema.md](%s/schema.md) | %s |\n",
			f.Name, f.ImportPath, f.Name, fixtures)
	}
	return os.WriteFile(filepath.Join(dir, "README.md"), b.Bytes(), 0644)
}

// goPackageDir resolves a package's source directory in the project's module
// context (typically the module cache).
func goPackageDir(projectDir, importPath string) (string, error) {
	goPath, err := exec.LookPath("go")
	if err != nil {
		return "", err
	}
	cmd := exec.Command(goPath, "list", "-f", "{{.Dir}}", importPath)
	cmd.Dir = projectDir
	out, err := cmd.Output()
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok && len(ee.Stderr) > 0 {
			return "", fmt.Errorf("%s", strings.TrimSpace(string(ee.Stderr)))
		}
		return "", err
	}
	dir := strings.TrimSpace(string(out))
	if dir == "" {
		return "", fmt.Errorf("package %s has no local source (run `go get %s`)", importPath, importPath)
	}
	return dir, nil
}

// copyFile copies src to dst with writable permissions (module-cache files
// are read-only).
func copyFile(src, dst string) error {
	data, err := os.ReadFile(src)
	if err != nil {
		return err
	}
	return os.WriteFile(dst, data, 0644)
}

// copyDir recursively copies a directory tree.
func copyDir(src, dst string) error {
	entries, err := os.ReadDir(src)
	if err != nil {
		return err
	}
	if err := os.MkdirAll(dst, 0755); err != nil {
		return err
	}
	for _, e := range entries {
		s, d := filepath.Join(src, e.Name()), filepath.Join(dst, e.Name())
		if e.IsDir() {
			if err := copyDir(s, d); err != nil {
				return err
			}
			continue
		}
		if err := copyFile(s, d); err != nil {
			return err
		}
	}
	return nil
}
