package formats

import (
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// The resolver matrix: the markdown alias, convention short names, full
// third-party paths, and the failure modes. No hardcoded module list beyond
// the alias — a short name resolves whether or not the module exists (go get
// reports typos).
func TestResolve(t *testing.T) {
	tests := []struct {
		name    string
		symbol  string
		want    Format
		wantErr string
	}{
		{name: "markdown", want: Format{Name: "markdown", ImportPath: "github.com/gofuego/fuego/parsers/markdown", Symbol: "markdown"}},
		{name: "openapi", want: Format{Name: "openapi", ImportPath: "github.com/gofuego/fuego-formats/openapi", Symbol: "openapi"}},
		{name: "notyetinvented", want: Format{Name: "notyetinvented", ImportPath: "github.com/gofuego/fuego-formats/notyetinvented", Symbol: "notyetinvented"}},
		{name: "github.com/acme/terraform", want: Format{Name: "terraform", ImportPath: "github.com/acme/terraform", Symbol: "terraform"}},
		{name: "github.com/acme/fuego-terraform", wantErr: "--symbol"},
		{name: "github.com/acme/fuego-terraform", symbol: "terraform", want: Format{Name: "fuego-terraform", ImportPath: "github.com/acme/fuego-terraform", Symbol: "terraform"}},
		{name: "bad-short", wantErr: "not a valid Go identifier"},
		{name: "", wantErr: "empty"},
		{name: "openapi", symbol: "not-ident", wantErr: "not a valid Go identifier"},
	}
	for _, tt := range tests {
		got, err := ResolveWithSymbol(tt.name, tt.symbol)
		if tt.wantErr != "" {
			if err == nil || !strings.Contains(err.Error(), tt.wantErr) {
				t.Errorf("Resolve(%q, %q) error = %v, want containing %q", tt.name, tt.symbol, err, tt.wantErr)
			}
			continue
		}
		if err != nil {
			t.Errorf("Resolve(%q, %q): %v", tt.name, tt.symbol, err)
			continue
		}
		if got != tt.want {
			t.Errorf("Resolve(%q, %q) = %+v, want %+v", tt.name, tt.symbol, got, tt.want)
		}
	}
}

// RenderFile → ParseFile must round-trip, including named imports for
// symbols that differ from the path base and the markdown alias.
func TestRenderParseRoundTrip(t *testing.T) {
	in := []Format{
		{Name: "markdown", ImportPath: "github.com/gofuego/fuego/parsers/markdown", Symbol: "markdown"},
		{Name: "openapi", ImportPath: "github.com/gofuego/fuego-formats/openapi", Symbol: "openapi"},
		{Name: "fuego-terraform", ImportPath: "github.com/acme/fuego-terraform", Symbol: "terraform"},
	}
	dir := t.TempDir()
	if err := WriteFile(dir, in); err != nil {
		t.Fatal(err)
	}

	src, _ := os.ReadFile(filepath.Join(dir, FileName))
	for _, want := range []string{
		"Code generated by fuego; DO NOT EDIT.",
		"func registerFormats(eng *engine.Engine)",
		"eng.Register(markdown.Parser())",
		"eng.Register(openapi.Parser())",
		"eng.Register(terraform.Parser())",
		"terraform \"github.com/acme/fuego-terraform\"",
	} {
		if !strings.Contains(string(src), want) {
			t.Errorf("formats.go missing %q:\n%s", want, src)
		}
	}

	got, err := ParseFile(dir)
	if err != nil {
		t.Fatal(err)
	}
	if !reflect.DeepEqual(got, in) {
		t.Errorf("round trip = %+v, want %+v", got, in)
	}
}

func TestParseFileAbsent(t *testing.T) {
	if _, err := ParseFile(t.TempDir()); !os.IsNotExist(err) {
		t.Errorf("want os.ErrNotExist for a project without %s, got %v", FileName, err)
	}
}

// The materializer copies schema.md (required), DEPENDENCIES.md (optional),
// and the testdata tree, making module-cache read-only files writable.
func TestMaterializeFromDir(t *testing.T) {
	pkg := t.TempDir()
	os.WriteFile(filepath.Join(pkg, "schema.md"), []byte("# x — parser contract\n"), 0444)
	os.MkdirAll(filepath.Join(pkg, "testdata"), 0755)
	os.WriteFile(filepath.Join(pkg, "testdata", "a.x"), []byte("in"), 0444)
	os.WriteFile(filepath.Join(pkg, "testdata", "a.golden.json"), []byte("{}"), 0444)

	project := t.TempDir()
	f := Format{Name: "x", ImportPath: "example.com/x", Symbol: "x"}
	if err := materializeFromDir(pkg, project, f); err != nil {
		t.Fatal(err)
	}

	for _, rel := range []string{"docs/formats/x/schema.md", "docs/formats/x/testdata/a.x", "docs/formats/x/testdata/a.golden.json"} {
		p := filepath.Join(project, filepath.FromSlash(rel))
		info, err := os.Stat(p)
		if err != nil {
			t.Errorf("missing %s: %v", rel, err)
			continue
		}
		if info.Mode().Perm()&0200 == 0 {
			t.Errorf("%s copied read-only", rel)
		}
	}

	// No schema.md → an error naming the format.
	empty := t.TempDir()
	if err := materializeFromDir(empty, project, f); err == nil || !strings.Contains(err.Error(), "schema.md") {
		t.Errorf("want schema.md error, got %v", err)
	}
}

func TestWriteIndex(t *testing.T) {
	project := t.TempDir()
	fmts := []Format{
		{Name: "openapi", ImportPath: "github.com/gofuego/fuego-formats/openapi", Symbol: "openapi"},
		{Name: "markdown", ImportPath: "github.com/gofuego/fuego/parsers/markdown", Symbol: "markdown"},
	}
	// openapi has fixtures on disk; markdown doesn't (yet).
	os.MkdirAll(filepath.Join(project, "docs", "formats", "openapi", "testdata"), 0755)

	if err := WriteIndex(project, fmts); err != nil {
		t.Fatal(err)
	}
	idx, err := os.ReadFile(filepath.Join(project, "docs", "formats", "README.md"))
	if err != nil {
		t.Fatal(err)
	}
	got := string(idx)
	// Sorted by name, fixtures linked only when present.
	if !strings.Contains(got, "[schema.md](openapi/schema.md)") || !strings.Contains(got, "[testdata/](openapi/testdata)") {
		t.Errorf("openapi row wrong:\n%s", got)
	}
	if !strings.Contains(got, "[schema.md](markdown/schema.md)") {
		t.Errorf("markdown row missing:\n%s", got)
	}
	if strings.Index(got, "| markdown |") > strings.Index(got, "| openapi |") {
		t.Errorf("index not sorted by name:\n%s", got)
	}
}
